version: "3.9"

services:
  database-service:
    image: mongo
    container_name: database-service
    ports:
      - 27017:27017
    restart: always
    networks: 
      - shared-network

  db-seed-service:
    depends_on:
      - database-service
    networks:
     - shared-network
    links: 
      - database-service
    build:
      context: ./database
      dockerfile: Dockerfile

  api-service:
    networks: 
      - shared-network
    environment:
      - "MONGO_URI=mongodb://database-service:27017/spot"
    depends_on:
      - database-service
    ports:
      - 3000:3000
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    links:
      - database-service

 

networks:
  shared-network:

volumes:
  mongodata: